name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry (only if on release branch)
      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/release'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }} .

      # Push the Docker image to GitHub Container Registry (only if on release branch)
      - name: Push Docker image
        if: github.ref == 'refs/heads/release'
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}
          